-- Oracle SQL Schema Definition (for SQL*Plus)
-- Drop tables if they exist (ignoring errors if they don't)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Notifications CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Payments CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Registrations CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Events CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE Users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR2(50) NOT NULL CHECK (role IN ('Admin', 'Organizer', 'Attendee')),
    username VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Events (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    description CLOB,
    event_date DATE NOT NULL,
    event_time VARCHAR2(50) NOT NULL,
    venue VARCHAR2(255) NOT NULL,
    capacity NUMBER NOT NULL CHECK (capacity > 0),
    ticket_price NUMBER(10,2) DEFAULT 100.00,
    current_attendees NUMBER DEFAULT 0,
    organizer_id NUMBER NOT NULL,
    status VARCHAR2(50) DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'ongoing', 'completed')),
    image_url VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organizer_id) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE Registrations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    status VARCHAR2(50) DEFAULT 'registered' CHECK (status IN ('registered', 'cancelled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE,
    CONSTRAINT unique_reg UNIQUE(user_id, event_id)
);

CREATE TABLE Payments (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    event_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    status VARCHAR2(50) DEFAULT 'success' CHECK (status IN ('success', 'failed')),
    payment_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id),
    FOREIGN KEY (event_id) REFERENCES Events(id)
);

CREATE TABLE Notifications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message VARCHAR2(500) NOT NULL,
    is_read NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
);

-- Triggers

CREATE OR REPLACE TRIGGER after_registration_insert
AFTER INSERT ON Registrations
FOR EACH ROW
BEGIN
    IF :NEW.status = 'registered' THEN
        UPDATE Events SET current_attendees = current_attendees + 1 WHERE id = :NEW.event_id;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER after_event_update
AFTER UPDATE ON Events
FOR EACH ROW
BEGIN
    IF :OLD.venue != :NEW.venue OR :OLD.event_date != :NEW.event_date THEN
        INSERT INTO Notifications (user_id, message)
        SELECT user_id, 'The event ' || :NEW.title || ' has been updated. New Date: ' || :NEW.event_date || ', Venue: ' || :NEW.venue
        FROM Registrations
        WHERE event_id = :NEW.id AND status = 'registered';
    END IF;
END;
/

-- Stored Procedures

CREATE OR REPLACE PROCEDURE register_user_for_event(
    p_user_id IN NUMBER, 
    p_event_id IN NUMBER, 
    p_amount IN NUMBER, 
    p_status OUT VARCHAR2
) AS
    v_capacity NUMBER;
    v_attendees NUMBER;
    v_existing NUMBER := 0;
BEGIN
    SELECT capacity, current_attendees INTO v_capacity, v_attendees FROM Events WHERE id = p_event_id FOR UPDATE;
    
    SELECT COUNT(*) INTO v_existing FROM Registrations WHERE user_id = p_user_id AND event_id = p_event_id AND status = 'registered';

    IF v_existing > 0 THEN
        p_status := 'already_registered';
        ROLLBACK;
    ELSIF v_attendees >= v_capacity THEN
        p_status := 'full';
        ROLLBACK;
    ELSE
        -- Process simulated payment
        INSERT INTO Payments (user_id, event_id, amount, status) VALUES (p_user_id, p_event_id, p_amount, 'success');
        
        -- Insert registration (Trigger updates current_attendees)
        INSERT INTO Registrations (user_id, event_id, status) VALUES (p_user_id, p_event_id, 'registered');
        
        -- Notification
        INSERT INTO Notifications (user_id, message) VALUES (p_user_id, 'Successfully registered for Event ID: ' || p_event_id);
        
        p_status := 'success';
        COMMIT;
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        p_status := 'failed';
END;
/

CREATE OR REPLACE PROCEDURE cancel_registration(p_user_id IN NUMBER, p_event_id IN NUMBER) AS
    v_status VARCHAR2(50);
BEGIN
    SELECT status INTO v_status FROM Registrations WHERE user_id = p_user_id AND event_id = p_event_id FOR UPDATE;
    
    IF v_status = 'registered' THEN
        UPDATE Registrations SET status = 'cancelled' WHERE user_id = p_user_id AND event_id = p_event_id;
        UPDATE Events SET current_attendees = current_attendees - 1 WHERE id = p_event_id;
        
        INSERT INTO Notifications (user_id, message) VALUES (p_user_id, 'Your registration for Event ID ' || p_event_id || ' has been cancelled.');
    END IF;
    
    COMMIT;
END;
/
